[package]
name = "kal"
version = "0.1.0"
description = "Keyboard-driven app launcher and productivity tool."
authors = [ "Amr Bashir <amr.bashir2015@gmail.com>" ]
repository = "https://github.com/amrbashir/kal"
license = "MIT"
edition = "2021"
rust-version = "1.56"

[[bin]]
name = "kal"
path = "src/core/main.rs"

[dependencies]
wry = { git = "https://github.com/tauri-apps/wry", branch="dev", features = ["protocol"] }
serde = "1.0.117"
serde_json = "1.0.78"
rust-embed="6.3.0"

[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao", branch="fix/windows/set-size-overflow" }

