[package]
name = "kal"
version = "0.0.0"
description = "Keyboard-driven app launcher and productivity tool."
authors = [ "Amr Bashir <amr.bashir2015@gmail.com>" ]
repository = "https://github.com/amrbashir/kal"
license = "MIT"
edition = "2021"
rust-version = "1.61"

[[bin]]
name = "kal"
path = "src/core/main.rs"

[dependencies]
wry = { git = "https://github.com/tauri-apps/wry", branch="dev", features = ["protocol"] }
serde = "1.0"
serde_json = "1.0"
rust-embed= "6.4"
serialize-to-javascript = "0.1"
fuzzy-matcher = "0.3"
dirs-next = "2.0"
percent-encoding = "2.1"
dunce = "1.0"
anyhow = "1.0"

[target.'cfg(target_os = "windows")'.dependencies]
webview2-com = "0.16"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.36"
features = [
  "Win32_UI_Shell",
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_UI_WindowsAndMessaging",
]
